# Setup

In [1]:
%load_ext autoreload
%autoreload 2
import datetime
import os
import pandas as pd

from SFRCalibration import *

## Define parameters

In [2]:
geometry = ['2SEG', 'nSEG']
elevation = ['LIDAR', 'GNSS']

# Define the target values for flow and depth
flow_target = 0.019  # m3/s
depth_target = 0.20   # m

# Set the print of model runs to silent
silent = True # True: the MODFLOW runs will not be printed in the terminal

# Calubration parameters
parameters_sets = {
    0: {
        'file_path': r'C:\repos\fontanile_model\runs\busca_sfr_data_2seg.xlsx',
        'modelname': 'busca_base_infittito_apr24_sfr_icalc1',
        'model_ws': r'C:\repos\fontanile_model\models\Busca_SFR_1',
        'seg_t': 1,
        'seg_a': [2],
        'tseg': True,
        'reach_t': 9,
        'k_dict': {
            'kt': [1e-5, 5.5e-5, 1e-4, 5.5e-4, 1e-3], 
            'ka': [1e-6, 5.5e-6, 1e-5, 5.5e-5, 1e-4] 
        },
        's_dict': {
                'st': [0.0033, 0.0022,	0.0011],
                'sa': [0.0033, 0.0022,	0.0011]
        },
        'geom': '2SEG',
        'icalc': 1,
        'elev': 'GNSS',
        'reach': 62,
        'segment': 2,
        'flow_target': 0.019,  # m3/s
        'depth_target': 0.20,   # m
        'silent': True
    },
    1: {
        'file_path': r'C:\repos\fontanile_model\runs\busca_sfr_data_2seg.xlsx',
        'modelname': 'busca_base_infittito_apr24_sfr_icalc1',
        'model_ws': r'C:\repos\fontanile_model\models\Busca_SFR_1',
        'seg_t': 1,
        'seg_a': [2],
        'tseg': True,
        'reach_t': 9,
        'k_dict': {
            'kt': [1e-5, 5.5e-5, 1e-4, 5.5e-4, 1e-3], 
            'ka': [1e-6, 5.5e-6, 1e-5, 5.5e-5, 1e-4] 
        },
        's_dict': {
                'st': [0.0033, 0.0022,	0.0011],
                'sa': [0.0033, 0.0022,	0.0011]
        },
        'geom': '2SEG',
        'icalc': 1,
        'elev': 'LIDAR',
        'reach': 62,
        'segment': 2,
        'flow_target': 0.019,  # m3/s
        'depth_target': 0.20,   # m
        'silent': True
    },
    2: {
        'file_path': r'C:\repos\fontanile_model\runs\busca_sfr_data_nseg.xlsx',
        'modelname': 'busca_base_infittito_apr24_sfr_icalc1',
        'model_ws': r'C:\repos\fontanile_model\models\Busca_SFR_1',
        'seg_t': 1,
        'seg_a': [2,3,4,5,6,7,8],
        'tseg': True,
        'reach_t': 9,
        'k_dict': {
            'kt': [1e-5, 5.5e-5, 1e-4, 5.5e-4, 1e-3], 
            'ka': [1e-6, 5.5e-6, 1e-5, 5.5e-5, 1e-4] 
        },
        's_dict': {
                'st': [0.002388,	0.001592,	7.96E-04],
                'sa': [
                    [0.002388,	0.001592,	7.96E-04],
                    [0.000426,	0.000284,	1.42E-04],
                    [0.000978,	0.000652,	3.26E-04],
                    [0.00456,	0.00304,	1.52E-03],
                    [0.002667,	0.001778,	8.89E-04],
                    [0.002646,	0.001764,	8.82E-04],
                    [0.01164,	0.00776,	3.88E-03]]
        },
        'geom': 'nSEG',
        'elev': 'LIDAR',
        'icalc': 1,
        'reach': 1,
        'segment': 3,
        'flow_target': 0.019,  # m3/s
        'depth_target': 0.20,   # m
        'silent': True
    },
    3: {
        'file_path': r'C:\repos\fontanile_model\runs\busca_sfr_data_nseg.xlsx',
        'modelname': 'busca_base_infittito_apr24_sfr_icalc1',
        'model_ws': r'C:\repos\fontanile_model\models\Busca_SFR_1',
        'seg_t': 1,
        'seg_a': [2,3,4,5,6,7,8],
        'tseg': True,
        'reach_t': 9,
        'k_dict': {
            'kt': [1e-5, 5.5e-5, 1e-4, 5.5e-4, 1e-3], 
            'ka': [1e-6, 5.5e-6, 1e-5, 5.5e-5, 1e-4] 
        },
        's_dict': {
                'st': [0.002388,	0.001592,	7.96E-04],
                'sa': [
                    [0.002388,	0.001592,	7.96E-04],
                    [0.000426,	0.000284,	1.42E-04],
                    [0.000978,	0.000652,	3.26E-04],
                    [0.00456,	0.00304,	1.52E-03],
                    [0.002667,	0.001778,	8.89E-04],
                    [0.002646,	0.001764,	8.82E-04],
                    [0.01164,	0.00776,	3.88E-03]]
        },
        'geom': 'nSEG',
        'elev': 'LIDAR',
        'icalc': 2,
        'n': [0.030, 0.035, 0.040],
        'reach': 1,
        'segment': 3,
        'flow_target': 0.019,  # m3/s
        'depth_target': 0.20,   # m
        'silent': True
    },
}

# Loop

In [45]:
start = datetime.datetime.now()
sfr = SFRCalibrator(parameters_sets[3])
sfr.n_runs()
sfr.load()
tool = pd.DataFrame(sfr.reach_data).copy()

segment_data = pd.DataFrame(sfr.segment_data[0]).copy()
segment_data.roughch = 100
segment_data.roughbk = 100

sfr.set_package(reach_data=tool, segment_data=segment_data)

Based on the parameters set:

- 492075 runs will be executed
- Approximately 246037.5 s will be needed (2.84765625 days)

In [44]:
segment_data

,nseg,icalc,outseg,iupseg,flow,runoff,etsw,pptsw,roughch,width1,width2,roughbk
0,1,1,2,0,0,0,0,0,100,7.82,7.82,100
1,2,1,3,0,0,0,0,0,100,7.82,4.36,100
2,3,2,4,0,0,0,0,0,100,4.36,4.36,100
3,4,2,5,0,0,0,0,0,100,3.14,3.14,100
4,5,2,6,0,0,0,0,0,100,3.08,3.08,100
5,6,2,7,0,0,0,0,0,100,3.08,3.08,100
6,7,2,8,0,0,0,0,0,100,3.05,3.05,100
7,8,2,0,0,0,0,0,0,100,2.54,2.54,100

In [8]:
# Load the data

i = 1
for run in parameters_sets.keys():
        run = 1
        if i > 100:
                # sfr.save_results(i, overpass = True)
                break

        start = datetime.datetime.now()
        sfr = SFRCalibrator(parameters_sets[run])
        sfr.n_runs()
        sfr.load()
        
        if sfr.geom == '2SEG':
                for kt in sfr.k_dict['kt']:
                        tool = pd.DataFrame(sfr.reach_data).copy()
                        tool.loc[sfr.find_cond(True), 'strhc1'] = kt
                        for ka in sfr.k_dict['ka']:
                                tool.loc[sfr.find_cond(False), 'strhc1'] = ka
                                for st in sfr.s_dict['st']:
                                        tool.loc[sfr.find_cond(True), 'slope'] = st
                                        for sa in sfr.s_dict['sa']:
                                                tool.loc[sfr.find_cond(False), 'slope'] = sa
                                                
                                                sfr.set_package(reach_data=tool)

                                                sfr.store_params(params = [kt, ka, st, sa],
                                                                labels = ['kt','ka', 'st', 'sa'],
                                                                modelcode = f'M{i}')
                                                
                                                sfr.run()

                                                sfr.load_results()

                                                sfr.save_results(i)

                                                # Progress the counter to generate the model code
                                                i += 1
        
        elif sfr.geom == 'nSEG' and sfr.icalc == 1:
                for kt in sfr.k_dict['kt']:
                        # Transform reach_data to a pandas.DataFrame
                        tool = pd.DataFrame(sfr.reach_data).copy()
                        # Change hydraulic conductivity and slope in the segments
                        if not sfr.tseg:
                                tool.loc[(tool.iseg == sfr.seg_t) & (tool.ireach <= sfr.reach_t), 'strhc1'] = kt
                        else:
                                tool.loc[tool.iseg == sfr.seg_t, 'strhc1'] = kt
                        for ka in sfr.k_dict['ka']:
                                tool.loc[tool.iseg != sfr.seg_t, 'strhc1'] = ka
                                if not sfr.tseg:
                                        tool.loc[(tool.iseg == sfr.seg_t) & (tool.ireach > sfr.reach_t), 'strhc1'] = ka
                                for st in sfr.s_dict['st']:
                                        if not sfr.tseg:
                                                tool.loc[(tool.iseg == sfr.seg_t) & (tool.ireach <= sfr.reach_t), 'slope'] = st
                                        else:
                                                tool.loc[tool.iseg == sfr.seg_t, 'slope'] = st
                                        for sa1 in sfr.s_dict['sa'][0]:
                                                if sfr.seg_a[0] == sfr.seg_t and not sfr.tseg:
                                                        tool.loc[(tool.iseg == sfr.seg_a[0]) & (tool.ireach > sfr.reach_t), 'slope'] = sa1
                                                else:
                                                        tool.loc[tool.iseg == sfr.seg_a[0], 'slope'] = sa1
                                                for sa2 in sfr.s_dict['sa'][1]:
                                                        tool.loc[tool.iseg == sfr.seg_a[1], 'slope'] = sa2
                                                        for sa3 in sfr.s_dict['sa'][2]:
                                                                tool.loc[tool.iseg == sfr.seg_a[2], 'slope'] = sa3
                                                                for sa4 in sfr.s_dict['sa'][3]:
                                                                        tool.loc[tool.iseg == sfr.seg_a[3], 'slope'] = sa4
                                                                        for sa5 in sfr.s_dict['sa'][4]:
                                                                                tool.loc[tool.iseg == sfr.seg_a[4], 'slope'] = sa5                                    
                                                                                for sa6 in sfr.s_dict['sa'][5]:
                                                                                        tool.loc[tool.iseg == sfr.seg_a[5], 'slope'] = sa6
                                                                                        for sa7 in sfr.s_dict['sa'][6]:
                                                                                                tool.loc[tool.iseg == sfr.seg_a[6], 'slope'] = sa7
                                                                                                
                                                                                                sfr.set_package(reach_data=tool)

                                                                                                sas = [st, sa1, sa2, sa3, sa4, sa5, sa6, sa7]
                                                                                                sfr.store_params(params = [kt, ka] + sas,
                                                                                                                labels = ['kt','ka', 'st'] + [f'sa{x}' for x in range(1, len(sfr.seg_a)+1)],
                                                                                                                modelcode=f'M{i}')

                                                                                                sfr.run()

                                                                                                sfr.save_results(i)
                                                                                                # Progress the counter to generate the model code
                                                                                                i += 1
        elif sfr.geom == 'nSEG' and sfr.icalc == 2:
                columns = ['m_code', 'kt','ka', 'st', 'n'] + [f'sa{x}' for x in range(1, len(sfr.seg_a)+1)] + ['flow_out_reach', 'stream_depth']

                for kt in sfr.k_dict['kt']:
                        # Transform reach_data to a pandas.DataFrame
                        tool = pd.DataFrame(sfr.reach_data).copy()
                        # Change hydraulic conductivity and slope in the segments
                        if not sfr.tseg:
                                tool.loc[(tool.iseg == sfr.seg_t) & (tool.ireach <= sfr.reach_t), 'strhc1'] = kt
                        else:
                                tool.loc[tool.iseg == sfr.seg_t, 'strhc1'] = kt
                        for ka in sfr.k_dict['ka']:
                                tool.loc[tool.iseg != sfr.seg_t, 'strhc1'] = ka
                                if not sfr.tseg:
                                        tool.loc[(tool.iseg == sfr.seg_t) & (tool.ireach > sfr.reach_t), 'strhc1'] = ka
                                for st in sfr.s_dict['st']:
                                        if not sfr.tseg:
                                                tool.loc[(tool.iseg == sfr.seg_t) & (tool.ireach <= sfr.reach_t), 'slope'] = st
                                        else:
                                                tool.loc[tool.iseg == sfr.seg_t, 'slope'] = st
                                for sa1 in sfr.s_dict['sa'][0]:
                                        if sfr.seg_a[0] == sfr.seg_t and not sfr.tseg:
                                                tool.loc[(tool.iseg == sfr.seg_a[0]) & (tool.ireach > sfr.reach_t), 'slope'] = sa1
                                        else:
                                                tool.loc[tool.iseg == sfr.seg_a[0], 'slope'] = sa1
                                        for sa2 in sfr.s_dict['sa'][1]:
                                                tool.loc[tool.iseg == sfr.seg_a[1], 'slope'] = sa2
                                                for sa3 in sfr.s_dict['sa'][2]:
                                                        tool.loc[tool.iseg == sfr.seg_a[2], 'slope'] = sa3
                                                        for sa4 in sfr.s_dict['sa'][3]:
                                                                tool.loc[tool.iseg == sfr.seg_a[3], 'slope'] = sa4
                                                                for sa5 in sfr.s_dict['sa'][4]:
                                                                        tool.loc[tool.iseg == sfr.seg_a[4], 'slope'] = sa5                                    
                                                                        for sa6 in sfr.s_dict['sa'][5]:
                                                                                tool.loc[tool.iseg == sfr.seg_a[5], 'slope'] = sa6
                                                                                for sa7 in sfr.s_dict['sa'][6]:
                                                                                        tool.loc[tool.iseg == sfr.seg_a[6], 'slope'] = sa7
                                                                                        for n in sfr.n:
                                                                                                segment_data = pd.DataFrame(sfr.segment_data).copy()
                                                                                                segment_data.ROUGHCH = n
                                                                                                segment_data.ROUGHBK = n

                                                                                                sfr.set_package(reach_data=tool, segment_data=segment_data)

                                                                                                sas = [st, sa1, sa2, sa3, sa4, sa5, sa6, sa7]
                                                                                                sfr.store_params(params = [kt, ka, n] + sas,
                                                                                                                labels = ['kt','ka', 'n', 'st'] + [f'sa{x}' for x in range(1, len(sfr.seg_a)+1)],
                                                                                                                modelcode=f'M{i}')

                                                                                                sfr.run()

                                                                                                sfr.save_results(i)
                                                                                                # Progress the counter to generate the model code
                                                                                                i += 1
        
        sfr.save_results(i, overpass = True)

        end = datetime.datetime.now()
        print('Runs terminated')
        print('Run code: ')
        print('Number of runs: ', i-1)
        elapsed = end - start
        print('Elapsed time (s): ', f'{elapsed.total_seconds():.4f}')
        print('Elapsed time (h): ', f'{elapsed.total_seconds()/3600:.6f}')
        print('Elapsed time (d): ', f'{elapsed.total_seconds()/(24*3600):.6f}')

Based on the parameters set:

- 225 runs will be executed
- Approximately 112.5 s will be needed (0.0013020833333333333 days)
Runs terminated
Run code:
Number of runs:  225
Elapsed time (s):  117.0684
Elapsed time (h):  0.032519
Elapsed time (d):  0.001355

# Load output

In [10]:
geom = '2SEG'
icalc = 1
elev = 'LIDAR'

In [11]:
params_save = pd.read_csv(os.path.join(sfr.model_ws, 'run_output', f'sfr_results_{geom}_ICALC{icalc}_{elev}_M{i-1}.csv'))

In [12]:
params_save.sort_values('depth_perc_err', ascending=True)

,Unnamed: 0,kt,ka,st,sa,flow_out_reach,stream_depth,geom,icalc,elev,flow_diff,depth_diff,flow_perc_err,depth_perc_err,combined_perc_err
218,M219,0.00100,0.000100,0.0033,0.0011,0.113930,0.19670,2SEG,1,LIDAR,-0.094930,0.00330,4.996316,0.01650,2.506408
221,M222,0.00100,0.000100,0.0022,0.0011,0.113380,0.19610,2SEG,1,LIDAR,-0.094380,0.00390,4.967368,0.01950,2.493434
224,M225,0.00100,0.000100,0.0011,0.0011,0.112300,0.19500,2SEG,1,LIDAR,-0.093300,0.00500,4.910526,0.02500,2.467763
209,M210,0.00100,0.000055,0.0033,0.0011,0.108400,0.19090,2SEG,1,LIDAR,-0.089400,0.00910,4.705263,0.04550,2.375382
212,M213,0.00100,0.000055,0.0022,0.0011,0.107830,0.19030,2SEG,1,LIDAR,-0.088830,0.00970,4.675263,0.04850,2.361882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,M2,0.00001,0.000001,0.0033,0.0022,0.003536,0.01988,2SEG,1,LIDAR,0.015464,0.18012,0.813905,0.90060,0.857253
7,M8,0.00001,0.000001,0.0011,0.0022,0.003529,0.01986,2SEG,1,LIDAR,0.015471,0.18014,0.814258,0.90070,0.857479
0,M1,0.00001,0.000001,0.0033,0.0033,0.003537,0.01761,2SEG,1,LIDAR,0.015463,0.18239,0.813837,0.91195,0.862893
3,M4,0.00001,0.000001,0.0022,0.0033,0.003535,0.01760,2SEG,1,LIDAR,0.015465,0.18240,0.813953,0.91200,0.862976
6,M7,0.00001,0.000001,0.0011,0.0033,0.003530,0.01759,2SEG,1,LIDAR,0.015470,0.18241,0.814184,0.91205,0.863117

In [13]:
params_save.sort_values('flow_perc_err', ascending=True)

,Unnamed: 0,kt,ka,st,sa,flow_out_reach,stream_depth,geom,icalc,elev,flow_diff,depth_diff,flow_perc_err,depth_perc_err,combined_perc_err
71,M72,0.000055,0.00001,0.0011,0.0011,0.018996,0.06711,2SEG,1,LIDAR,0.000004,0.13289,0.000211,0.66445,0.332330
68,M69,0.000055,0.00001,0.0022,0.0011,0.019053,0.06723,2SEG,1,LIDAR,-0.000053,0.13277,0.002789,0.66385,0.333320
70,M71,0.000055,0.00001,0.0011,0.0022,0.019054,0.05461,2SEG,1,LIDAR,-0.000054,0.14539,0.002842,0.72695,0.364896
65,M66,0.000055,0.00001,0.0033,0.0011,0.019081,0.06729,2SEG,1,LIDAR,-0.000081,0.13271,0.004263,0.66355,0.333907
69,M70,0.000055,0.00001,0.0011,0.0033,0.019082,0.04840,2SEG,1,LIDAR,-0.000082,0.15160,0.004316,0.75800,0.381158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,M221,0.001000,0.00010,0.0022,0.0022,0.113370,0.15930,2SEG,1,LIDAR,-0.094370,0.04070,4.966842,0.20350,2.585171
221,M222,0.001000,0.00010,0.0022,0.0011,0.113380,0.19610,2SEG,1,LIDAR,-0.094380,0.00390,4.967368,0.01950,2.493434
216,M217,0.001000,0.00010,0.0033,0.0033,0.113910,0.14140,2SEG,1,LIDAR,-0.094910,0.05860,4.995263,0.29300,2.644132
218,M219,0.001000,0.00010,0.0033,0.0011,0.113930,0.19670,2SEG,1,LIDAR,-0.094930,0.00330,4.996316,0.01650,2.506408
217,M218,0.001000,0.00010,0.0033,0.0022,0.113930,0.15970,2SEG,1,LIDAR,-0.094930,0.04030,4.996316,0.20150,2.598908

In [17]:
params_save.sort_values('combined_perc_err', ascending=True)

,Unnamed: 0,kt,ka,st,sa,flow_out_reach,stream_depth,geom,icalc,elev,flow_diff,depth_diff,flow_perc_err,depth_perc_err,combined_perc_err
model,,,,,,,,,,,,,,,
71,M72,0.000055,0.00001,0.0011,0.0011,0.018996,0.06711,2SEG,1,LIDAR,0.000004,0.13289,0.000211,0.66445,0.332330
68,M69,0.000055,0.00001,0.0022,0.0011,0.019053,0.06723,2SEG,1,LIDAR,-0.000053,0.13277,0.002789,0.66385,0.333320
65,M66,0.000055,0.00001,0.0033,0.0011,0.019081,0.06729,2SEG,1,LIDAR,-0.000081,0.13271,0.004263,0.66355,0.333907
70,M71,0.000055,0.00001,0.0011,0.0022,0.019054,0.05461,2SEG,1,LIDAR,-0.000054,0.14539,0.002842,0.72695,0.364896
67,M68,0.000055,0.00001,0.0022,0.0022,0.019111,0.05471,2SEG,1,LIDAR,-0.000111,0.14529,0.005842,0.72645,0.366146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,M221,0.001000,0.00010,0.0022,0.0022,0.113370,0.15930,2SEG,1,LIDAR,-0.094370,0.04070,4.966842,0.20350,2.585171
217,M218,0.001000,0.00010,0.0033,0.0022,0.113930,0.15970,2SEG,1,LIDAR,-0.094930,0.04030,4.996316,0.20150,2.598908
222,M223,0.001000,0.00010,0.0011,0.0033,0.112260,0.14020,2SEG,1,LIDAR,-0.093260,0.05980,4.908421,0.29900,2.603711
219,M220,0.001000,0.00010,0.0022,0.0033,0.113360,0.14100,2SEG,1,LIDAR,-0.094360,0.05900,4.966316,0.29500,2.630658
216,M217,0.001000,0.00010,0.0033,0.0033,0.113910,0.14140,2SEG,1,LIDAR,-0.094910,0.05860,4.995263,0.29300,2.644132